apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: clickhouse-standalone
spec:
  clusterDef: clickhouse
  topology: standalone
  terminationPolicy: Delete
  componentSpecs:
    - name: clickhouse
      replicas: 1
      resources:
        limits:
          cpu: '0.5'
          memory: 1Gi
        requests:
          cpu: '0.5'
          memory: 1Gi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: "openebs-hostpath"
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
